
map_locations:
  ros__parameters:
    # Logic: Added room3 and room4. Renamed medical_shop to it_service_desk.
    locations: ["room1", "room2", "room3", "room4", "it_service_desk"]
    
    initial_pose: [0.0, 0.0, 0.0]

    room1: [4.570, -4.072, 0.0] # Storage: PCs AND Monitors (Red)
    room2: [7.179, -10.247, 0.0]   # Storage: Laptops (Green)
    
    # New rooms added to complement the storage capacity
    room3: [-0.0498, -11.261, 0.0]  # Storage: Accessories 
    room4: [1.019, -15.706, 0.0]    # Storage: Cables (Purple)
    
    it_service_desk: [0.523, -22.043, 0.0]  # IT Service Desk (Yellow)
